jobs: 5000
use-conda: true
immediate-submit: true
notemp: true
restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "../../snakemake_config/slurm.cemm/slurm-submit.py {dependencies}"
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 4
latency-wait: 120
