DATA:
  path: "<path_to_data_folder>"
  Benchmark5.5:
    folder_path: "benchmark5.5"
    pdb_path: "structures"
    pp_cases: "Table_BM5.5.xlsx"

  AntibodyBenchmark:
    folder_path: "antibody_benchmark"
    pdb_path: "pdbs"
    ab_ag_cases: "antibody_benchmark_cases.xlsx"
