wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1654854312
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      - 19
      4: 3.8.10
      5: 0.12.17
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
max_epochs:
  desc: null
  value: 100
max_num_nodes:
  desc: null
  value: 50
patience:
  desc: null
  value: 20
