#!/bin/bash

#SBATCH -N 1      # nodes requested
#SBATCH -n 1      # tasks requested
#SBATCH -c 30      # cores requested
#SBATCH --mem=100GB  # memory in Mb
#SBATCH -o out_train  # send stdout to outfile
#SBATCH -e error_train  # send stderr to errfile
#SBATCH -t 20:00:00  # max time requested in hour:minute:second
#SBATCH -q a100
#SBATCH --gres gpu:a100:1
#SBATCH --export ALL

srun --container-image=nvcr.io#nvidia/pytorch:22.02-py3 /root/miniconda3/envs/abag_cluster/bin/python /root/projects/ag_binding_affinity/src/abag_affinity/main.py $*
