from pathlib import Path

# data downloaded from https://github.com/amhummer/Graphinity/tree/main/data
project_root = Path(workflow.basedir).parents[2] # two directories above - absolute paths not working
out_folder = project_root / "results" / "synthetic_ddg" / "reduced_dataset"
in_folder = project_root / "resources" / "synthetic_ddg" / "data/naga03/not-backed-up/scratch/hummer/synth_aff_data/synthetic_ddg_dataset_for_sharing/synthetic_ddg_mutated_pdbs/"


def all_pdb_files(wildcards):
    for pdb in in_folder.glob("*.pdb"):
        yield out_folder / pdb.name

rule all:
    input:
        all_pdb_files


rule trim_complex:
    """
    """
    input:
        pdb=in_folder / "{pdb}.pdb",
    output:
        pdb=out_folder / "{pdb}.pdb",
    params:
        max_l_len=115,
        max_h_len=125
    conda: "ag_binding_diffusion3"
    resources:
        mem_mb=10000
    threads: 1
    script: "scripts/trim_complex.py"
