from pathlib import Path

# data downloaded from https://github.com/amhummer/Graphinity/tree/main/data
project_root = Path(workflow.basedir).parents[2] # two directories above - absolute paths not working
out_folder = project_root / "results" / "synthetic_ddg" / "pdbs"
in_folder = project_root / "resources" / "synthetic_ddg" / "data/naga03/not-backed-up/scratch/hummer/synth_aff_data/synthetic_ddg_dataset_for_sharing/synthetic_ddg_mutated_pdbs/"

# TODO load paths etc from config.yaml

def all_pdb_files(wildcards):
    for pdb in in_folder.glob("*.pdb"):
        yield out_folder / pdb.name

rule all:
    input:
        all_pdb_files


rule trim_complex:
    """
    """
    input:
        pdb=in_folder / "{pdb}.pdb",
    output:
        pdb=out_folder / "{pdb}.pdb",
    params:
        max_l_len=115,
        max_h_len=125
    conda: "ag_binding_diffusion3"
    resources:
        mem_mb=10000
    threads: 1
    script: "scripts/trim_complex.py"


rule prepare_dataset_csv:
    """
    Generate the CSV file with absolute labels
    """
    input:
        syn_df=project_root / "results" / "synthetic_ddg" / "ddg.csv",
        abag_df=project_root / "results" / "abag_affinity_dataset" / "abag_affinity_dataset.csv",  # TODO delete

        sabdab_summary=project_root / "resources" / "SAbDab" / "sabdab_summary.tsv"
    output:
        absolute=project_root / "results" / "synthetic_ddg" / "ddg_with_absolute_labels.csv",
        relative=project_root / "results" / "synthetic_ddg" / "ddg_with_relative_labels.csv"
    conda: "ag_binding_diffusion3"
    params:
        offset_neglogkd=8.0
    log:
        notebook="logs/prepare_dataset_csv.py.ipynb"
    notebook:
        "scripts/prepare_dataset_csv.py.ipynb"
