from os.path import join
import os
from pathlib import Path

DATASET_NAME = "abag_affinity_dataset"

project_root = Path(workflow.basedir).parents[3] # two directories above - absolute paths not working
resource_folder = join(project_root, "resources")
results_folder = join(project_root, "results")

dataset_resource_folder = join(resource_folder, DATASET_NAME)
dataset_results_folder = join(results_folder, DATASET_NAME)

pdb_path = os.path.join(dataset_results_folder, "pdbs")
pdb_files = os.listdir(pdb_path)
pdb_ids = [ pdb_file.split(".")[0] for pdb_file in pdb_files ]

out_folder = join(results_folder, "force_field_tests", "abag_affinity", "FoldX")


rule all:
    input: out_folder + "/../foldx_results.csv"


# use not relaxed wildtype
rule analyze_complex:
    input:
        pdb_path + '/{pdb_id}.pdb'
    output:
        out_folder + "/Summary_{pdb_id}_AC.fxout"
    params:
        folder_path=pdb_path,
        out_folder=out_folder,
        pdb_id=r"{pdb_id}"
    shell: "FoldX --command=AnalyseComplex --pdb={params.pdb_id}.pdb --pdb-dir={params.folder_path} --output-dir={params.out_folder}"


rule aggregate_results:
    input: expand(out_folder + "/Summary_{pdb_id}_AC.fxout", pdb_id=pdb_ids),
    output:
        join(out_folder, "foldx_results.csv")
    conda:  join(project_root, "envs", "generation_environment.yml")
    script: "scripts/aggregate_energy_results.py"
