DATA:
  path: "data"

  AbDb:
    folder_path: "AbDb"
    pdb_paths:
      - "bound_wildtype"
      - "bound_relaxed"
      - "relaxed_unbound"
      - "relaxed_unbound_relaxed"
      - "unbound_relaxed"
      - "unbound_wildtype"
    summary: "abdb_summary.csv"

  SKEMPI.v2:
    folder_path: "SKEMPI_v2"
    summary: "cleaned_data.csv"
    mutated_pdb_path: "mutated_wildtype"
    affinity_type: "-log(Kd)"

  Dataset_v1:
    folder_path: "dataset_v1"
    pdb_path: ""
    summary: "dataset_v1.csv"
    affinity_type: "-log(Kd)"

  PDBBind:
    folder_path: "PDBBind"
    dataset_path: "data"
    summary: "pdbbind.csv"
    affinity_type: "-log(Kd)"

  AntibodyBenchmark:
    folder_path: "antibody_benchmark"
    pdb_paths:
      - "relaxed_pdbs"
      - "unrelaxed_pdbs"
    summary: "antibody_benchmark_scores.csv"
    affinity_type: "-log(Kd)"

  DMS:
    folder_path: "DMS"
    summary: "dms_infos.csv"
    mutated_pdb_path: "mutated"
    affinity_types:
      phillips21_bindin: "-log(Kd)"
      starr21_prosp_covid: "E"
      wu17_in: "E"
      wu20_differ_ha_h3_h1: "E"

RESOURCES:
  path: "resources"
  Benchmark5.5:
    folder_path: "benchmark5.5"
    pdb_path: "structures"
    summary: "Table_BM5.5.xlsx"

  AntibodyBenchmark:
    folder_path: "antibody_benchmark"
    pdb_path: "pdbs"
    summary: "antibody_benchmark_cases.xlsx"

  SAbDab:
    folder_path: "SAbDab"
    pdb_path: "pdbs"
    summary: "summary.tsv"

  AbDb:
    folder_path: "AbDb"
    pdb_path: "NR_LH_Protein_Martin"
    summary: "summary.csv"

  SKEMPI.v2:
    folder_path: "SKEMPI_v2"
    pdb_path: "PDBs"
    summary: "skempi_v2.csv"
    mutated_pdb_path: "mutated_wildtype"

  PDBBind:
    folder_path: "PDBBind"
    pdb_path: "PP"
    info_file: "PP/index/INDEX_general_PP.2020"
    summary: "cases.csv"
    dataset_path: "data"

  Dataset_v1:
    folder_path: "dataset_v1"
    pdb_path: "../AbDb/NR_LH_Protein_Martin"


RESULTS:
  path: "results"
  plot_path: "plots"
  processed_graph_path: "processed_graphs"
  cleaned_pdbs: "cleaned_pdb"

MODELS:
  Binding_DDG:
    model_path: "src/abag_affinity/binding_ddg_predictor/data/model.pt"

  DeepRefine:
    model_path: "../other_repos/DeepRefine/project/checkpoints/EGR_All_Atom_Models/LitPSR_EGR_AllAtomModel1_Seed42.ckpt"

TRAIN:
  standard:
    dataset: DMS-wu20_differ_ha_h3_h1:relative

  transfer:
    datasets:
      - PDBBind:absolute
      - SKEMPI.v2:absolute
      - SKEMPI.v2:relative
      - Dataset_v1:absolute

  bucket:
    datasets:
      - PDBBind:absolute
      - SKEMPI.v2:absolute
      - SKEMPI.v2:relative
      - Dataset_v1:absolute


HYPERPARAMETER_SEARCH:
  method: 'random'
  name: 'Hyperparameter_Search_2.0'
  metric:
    goal: 'maximize'
    name: 'Dataset_v1:absolute_val_corr'
  parameters:
    train_strategy:
      values:
        - "bucket_train"
        - "pretrain_model"
        - "model_train"
    pretrained_model:
      values:
        - ""
        - "DeepRefine"
        - "Binding_DDG"
    layer_type:
      values:
        - "GAT"
        - "GCN"
    gnn_type:
      values:
        - "proximity"
        - "guided"
    max_edge_distance:
      values:
        - 2
        - 3
        - 4
        - 5
      probabilities:
        - 0.1
        - 0.2
        - 0.3
        - 0.4
    num_gnn_layers:
      min: 0
      max: 15
    size_halving:
      values:
        - True
        - False
    aggregation_method:
      values:
        - "max"
        - "sum"
        - "mean"
        - "attention"
        - "fixed_size"
        - "edge"
    nonlinearity:
      values:
        - relu
        - leaky
        - gelu
    num_fc_layers:
      min: 1
      max: 5
    batch_size:
      min: 1
      max: 10
    learning_rate:
      max: 0.001
      min: 0.0000001
    node_type:
      values:
        - "atom"
        - "residue"
    loss_function:
      values:
        - "L1"
        - "L2"
    max_num_nodes:
      values:
        - 25
        - 50
        - 75
        - None
      probabilities:
        - 0.05
        - 0.1
        - 0.2
        - 0.65
    scale_values:
      values:
        - True
        - False