DATA:
  path: "data"

  AbDb:
    folder_path: "AbDb"
    pdb_paths:
      - "bound_wildtype"
      - "bound_relaxed"
      - "relaxed_unbound"
      - "relaxed_unbound_relaxed"
      - "unbound_relaxed"
      - "unbound_wildtype"
    summary: "abdb_summary.csv"

  SKEMPI.v2:
    folder_path: "SKEMPI_v2"
    summary: "cleaned_data.csv"
    mutated_pdb_path: "mutated_wildtype"

  Dataset_v1:
    folder_path: "dataset_v1"
    pdb_path: ""
    summary: "dataset_v1.csv"

  PDBBind:
    folder_path: "PDBBind"
    dataset_path: "data"
    summary: "pdbbind.csv"

  AntibodyBenchmark:
    folder_path: "antibody_benchmark"
    pdb_paths:
      - "relaxed_pdbs"
      - "unrelaxed_pdbs"
    summary: "antibody_benchmark_scores.csv"

  DMS:
    folder_path: "DMS"
    summary: "dms_curated.csv"
    mutated_pdb_path: "mutated"

RESOURCES:
  path: "resources"
  Benchmark5.5:
    folder_path: "benchmark5.5"
    pdb_path: "structures"
    summary: "Table_BM5.5.xlsx"

  AntibodyBenchmark:
    folder_path: "antibody_benchmark"
    pdb_path: "pdbs"
    summary: "antibody_benchmark_cases.xlsx"

  SAbDab:
    folder_path: "SAbDab"
    pdb_path: "pdbs"
    summary: "summary.tsv"

  AbDb:
    folder_path: "AbDb"
    pdb_path: "NR_LH_Protein_Martin"
    summary: "summary.csv"

  SKEMPI.v2:
    folder_path: "SKEMPI_v2"
    pdb_path: "PDBs"
    summary: "skempi_v2.csv"
    mutated_pdb_path: "mutated_wildtype"

  PDBBind:
    folder_path: "PDBBind"
    pdb_path: "PP"
    info_file: "PP/index/INDEX_general_PP.2020"
    summary: "cases.csv"
    dataset_path: "data"

  Dataset_v1:
    folder_path: "dataset_v1"
    pdb_path: "../AbDb/NR_LH_Protein_Martin"


RESULTS:
  path: "results"
  plot_path: "plots"
  processed_graph_path: "processed_graphs"
  cleaned_pdbs: "cleaned_pdb"

MODELS:
  binding_dgg_predictor:
    model_path: "ag_binding_affinity/binding_ddg_predictor/data/model.pt"

  deep_refine:
    model_path: "../other_repos/DeepRefine/project/checkpoints/EGR_All_Atom_Models/LitPSR_EGR_AllAtomModel1_Seed42.ckpt"

TRAIN:
  standard:
    dataset: Dataset_v1:absolute

  transfer:
    datasets:
      - PDBBind:absolute
      - SKEMPI.v2:absolute
      - SKEMPI.v2:relative
      - Dataset_v1:absolute

  bucket:
    datasets:
      - PDBBind:absolute
      - SKEMPI.v2:absolute
      - SKEMPI.v2:relative
      - Dataset_v1:absolute


HYPERPARAMETER_SEARCH:
  method: 'random'
  controller:
    type: "local"
  metric:
    goal: 'maximize'
    name: 'Dataset_v1:absolute_val_corr'
  parameters:
    model_type:
      values:
        - "GraphConv"
        - "GraphAttention"
        - "FixedSizeGraphConv"
        - "DDGBackboneFC"
        - "KpGNN"
        - "DeepRefineBackbone"
    train_strategy:
      values:
        - "bucket_train"
        - "pretrain_model"
        - "model_train"
    batch_size:
      values:
        - 1
        - 5
        - 10
    learning_rate:
      max: 0.001
      min: 0.0000001
    patience:
      min: 5
      max: 30
    node_type:
      values:
        - "atom"
        - "residue"
    loss_function:
      values:
        - "L1"
        - "L2"
    max_num_nodes:
      values:
        - 10
        - 30
        - 50
        - 80
    scale_values:
      values:
        - True
        - False
    interface_hull_size:
      values:
        - 5
        - 7
        - 10
    max_epochs:
      values:
        - 200