DATASETS:
  path: ""

  SKEMPI.v2:
    folder_path: "results/SKEMPI_v2"
    summary: "skempi_v2.csv"
    mutated_pdb_path: "mutated"
    relaxed_mutated_pdb_path: "mutated_relaxed"
    pdb_path: "mutated"
    affinity_type: "-log(Kd)"

  abag_affinity:
    folder_path: "results/abag_affinity_dataset"
    pdb_path: "pdbs"
    relaxed_pdb_path: "pdbs_relaxed"
    summary: "abag_affinity_dataset.csv"
    affinity_type: "-log(Kd)"

  abag_affinity_of_embeddings:
    folder_path: "results/abag_affinity_dataset"
    pdb_path: "pdbs"
    relaxed_pdb_path: "pdbs"
    summary: "abag_affinity_dataset.csv"
    of_embeddings: "of_embeddings"
    affinity_type: "-log(Kd)"

  PDBBind:
    folder_path: "results/PDBBind"
    pdb_path: "pdbs"
    relaxed_pdb_path: "pdbs_relaxed"
    summary: "pdbbind.csv"
    affinity_type: "-log(Kd)"

  AntibodyBenchmark:
    folder_path: "results/antibody_benchmark"
    pdb_path: "pdbs_bound"
    relaxed_pdb_path: "pdbs_relaxed"
    summary: "benchmark.csv"
    affinity_type: "-log(Kd)"

  DMS:
    folder_path: "results/DMS"
    summary: "" # summary for every subdataset
    mutated_pdb_path: "mutated"
    relaxed_mutated_pdb_path: "mutated"
    affinity_types:
      phillips21_bindin: "-log(Kd)"
      starr21_prosp_covid: "E"
      madan21_mutat_hiv: "E"
      wu17_in: "E"
      wu20_differ_ha_h3_h1: "E"
      mason21: "E"
      b.20_funct_screen_strat_engin_chimer: "E"

RESOURCES:
  path: ""

  DMS:
    folder_path: "data/DMS"
    info: "dms_curated.csv"

  SAbDab:
    folder_path: "resources/SAbDab"
    summary: "summary.tsv"

  AbDb:
    folder_path: "resources/AbDb"
    pdb_path: "pdbs"
    summary: "summary.csv"


RESULTS:
  path: "results"
  plot_path: "plots"
  prediction_path: "predictions"
  model_path: "models"
  force_field_results: "ff_res"
  processed_graph_path: "processed_graphs"
  interface_pdbs: "interface_pdb"

MODELS:
  Binding_DDG:
    model_path: "src/abag_affinity/binding_ddg_predictor/data/model.pt"

  DeepRefine:
    model_path: "../other_repos/DeepRefine/project/checkpoints/EGR_All_Atom_Models/LitPSR_EGR_AllAtomModel1_Seed42.ckpt"
  IPA:
    model_path: "../../resources/openfold_params/finetuning_ptm_2.pt"

HYPERPARAMETER_SEARCH:
  method: 'random'
  name: 'Initial-Hyperparameter-Search'
  metric:
    goal: 'minimize'
    name: 'abag_affinity:absolute_val_rmse'
  parameters:
    train_strategy:
      values:
        - "model_train"
    batch_size:
      values:
        - 1
        - 10
    learning_rate:
      min: 0.000001
      max: 0.001
    node_type:
      values:
        - "atom"
        - "residue"
    max_num_nodes:
      values:
        - 10
        - 50
        - None
    scale_values:
      values:
        - True
        - False
    loss_function:
      values:
        - "L1"
        - "L2"
    layer_type:
      values:
        - "GAT"
        - "GCN"
    gnn_type:
      values:
        - "proximity"
        - "guided"
    max_edge_distance:
      values:
        - 3
        - 5
    num_gnn_layers:
      values:
        - 0
        - 3
        - 7
    attention_heads:
      values:
        - 1
        - 3
        - 5
    channel_halving:
      values:
        - True
        - False
    channel_doubling:
      values:
        - True
        - False
    aggregation_method:
      values:
        - "max"
        - "mean"
        - "attention"
        - "edge"
    nonlinearity:
      values:
        - "relu"
        - "leaky"
        - "gelu"
    num_fc_layers:
      values:
        - 1
        - 3
        - 10
